//login
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';


//user
export const SET_USER_ID = 'SET_USER_ID';
export const DELETE_USER = 'DELETE_USER';

//profile
export const SET_PROFILE = 'SET_PROFILE';
export const OPEN_ADD_CONTACT_MODAL = 'OPEN_ADD_CONTACT_MODAL';

//friends
export const SET_FRIENDS = 'SET_FRIENDS';

//Lesson
export const SET_INCOMING_LESSON_POPUP = 'SET_INCOMING_LESSON_POPUP';
export const SET_OUTGOING_LESSON_POPUP = 'SET_OUTGOING_LESSON_POPUP';
export const SET_INCOMING_USER = 'SET_INCOMING_USER';
export const SET_OUTGOING_USER = 'SET_OUTGOING_USER';
export const SET_LESSON_ID = 'SET_LESSON_ID';
export const SET_FROM_USER_ID = 'SET_FROM_USER_ID';
export const SET_TO_USER_ID = 'SET_TO_USER_ID';
export const SET_LESSON_TITLE = 'SET_LESSON_TITLE';
